services:

  book_catalog:
    platform: linux/amd64  
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://mirahazall:lwoutTXmwiEsemV3PjnA8meGKdXhzV4A@dpg-cr5aa3bv2p9s73afd9bg-a.oregon-postgres.render.com/part3
    depends_on:
      - inventory_management
    restart: "no"

  inventory_management:
    platform: linux/amd64  
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://mirahazall:lwoutTXmwiEsemV3PjnA8meGKdXhzV4A@dpg-cr5aa3bv2p9s73afd9bg-a.oregon-postgres.render.com/part3
    restart: "no"
